cmd/list_discussions.go, lua/gitlab/discussions.lua, lua/gitlab/utils/init.lua
Reverts harrisoncramer/gitlab.nvim#14
This was causing issues with the jump to file location functionality
=> Revert "Feat: Pull down all non-code notes"

lua/gitlab/init.lua
=> Fix Discussion Tree Positioning

README.md, cmd/main.go, cmd/update.go, lua/gitlab/description.lua, lua/gitlab/init.lua, lua/gitlab/summary.lua, lua/gitlab/utils/init.lua
This MR will make it possible to edit the description of a pull request.
The description popup now has an action that will submit the buffer content to Gitlab's PR update API.
Resolves #20
=> Feat: Edit PR Description

README.md, cmd/approve.go, cmd/description.go, cmd/info.go, cmd/list_discussions.go, cmd/main.go, cmd/pipeline.go, cmd/reply.go, cmd/revisions.go, cmd/revoke.go, lua/gitlab/actions/discussions.lua, lua/gitlab/actions/pipeline.lua, lua/gitlab/init.lua, lua/gitlab/state.lua, lua/gitlab/utils/init.lua
This MR will make it possible to see the pipeline status of an MR and to re-run failed jobs in that pipeline.
=> Feat: View + Manage Pipeline

lua/gitlab/reviewer/diffview.lua, lua/gitlab/reviewer/init.lua
Related to #49 
I'm not sure, that I've thought through all corner cases, but looks like it good enough for the first draft
=> Diffview support

lua/gitlab/actions/pipeline.lua
Hi,
I noticed that sometimes I cannot get pipeline popup because `pipeline` in `state.INFO.pipeline` is `nil`. Based on [docs](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr) the field `head_pipeline` should be used instead. I updated the code so that it prefer `head_pipeline` and fallback to `pipeline`.
=> Prefer `head_pipeline` field when getting pipeline info

README.md, cmd/client.go, lua/gitlab/server.lua, lua/gitlab/state.lua
This MR improves the logging for the Go server by allowing users to log out the full request or response bodies in the setup function, aiding in debugging connectivity issues and other errors with the client-server data flow.
=> Feat: Improve Logging for Go Server

cmd/git_test.go
Just wanted to add few more tests just to be sure.
=> Extend tests for parsing git remote url

.github/workflows/go.yaml
Cleans up Go action to only run on merge request into main
=> Fix: Go Action Runs on MR Only

.github/workflows/tags.yaml
This MR fixes the tagging logic in our pipeline to automatically set a #patch value for the tag type.
=> Fix tagging

.github/workflows/tags.yaml
Apologies for the churn here, trying to fix the tagging CI!
=> Fix tagging 2

README.md
This is not part of the core repository and is not maintained as part of .gitlab.nvim, we don't to recommend unrelated code to users.
=> Updates Readme: Remove "Extra" Section

.github/workflows/tag-and-release.yaml
This MR adds an action to automatically generate a release based on the tags. Tags and releases are automatically created whenever a PR is merged into main.
=> Feat: Automatically Generate Releases

.github/workflows/tag-and-release.yaml, README.md, lua/gitlab/state.lua
Provide the ability to configure the location of the `.gitlab.nvim` file.
Fixes #116
=> Feat: Customize Config Path

lua/gitlab/reviewer/diffview.lua
This MR throws an error when a merge request has no changes.
=> Bugfix: Handle Merge Requests without Changes

cmd/git.go, cmd/git_test.go
This was erroneously removed during a recent refactor, adding it back
=> Fix: Adds Git Test File

lua/gitlab/actions/comment.lua, lua/gitlab/reviewer/location.lua
Fixes bug w/ #197 location provider initialization
=> Fix: Location Provider Class

lua/gitlab/actions/comment.lua, lua/gitlab/hunks/init.lua
=> fix: address mIssing get_lines function

cmd/client.go
=> fix: Log path

cmd/label.go, go.mod, go.sum, lua/gitlab/actions/labels.lua, lua/gitlab/actions/summary.lua
This is necessary to get the the "draft" changes, which are needed to support another feature request, see this MR https://github.com/xanzy/go-gitlab/pull/1905
=> fix: update go-gitlab and fix label code

lua/gitlab/actions/discussions/init.lua
The PR from #225 was targeting the wrong branch, this merges it into develop correctly
=> fix: line code fix

cmd/git.go, cmd/git_test.go
Same as https://github.com/harrisoncramer/gitlab.nvim/pull/220, and add a test case.
=> ssh remote url can have custom port

doc/gitlab.nvim.txt, lua/gitlab/actions/discussions/init.lua, lua/gitlab/init.lua, lua/gitlab/utils/init.lua
One less reason to go to the Web :)
This also cosmetically refactors code for getting the node url.
=> Feat: Copy web url of MR to clipboard

README.md, cmd/main.go, doc/gitlab.nvim.txt, lua/gitlab/actions/comment.lua, lua/gitlab/actions/common.lua, lua/gitlab/actions/create_mr.lua, lua/gitlab/actions/discussions/init.lua, lua/gitlab/actions/discussions/winbar.lua, lua/gitlab/actions/merge_requests.lua, lua/gitlab/actions/pipeline.lua, lua/gitlab/actions/summary.lua, lua/gitlab/git.lua, lua/gitlab/reviewer/init.lua, lua/gitlab/state.lua, lua/gitlab/utils/init.lua
This MR improves handling of commands (primarily git commands) run through the terminal by properly getting their exit codes and early aborting as appropriate.
It also lets the user toggle between 'live mode' and 'draft mode' which posts comments immediately or as drafts.
=> Draft: Wrap CLI commands

README.md, doc/gitlab.nvim.txt
We require some state from Packer, this fixes the docs to reflect a way to get around that.
=> fix: packer installation docs

README.md, doc/gitlab.nvim.txt
- Improve description of choose_merge_request()
- Add note about hard-coded "origin"
- Unify formatting
=> Docs: Small iprovements to README and docs

lua/gitlab/actions/create_mr.lua
=> Fix: Cycle create_mr popups when create_mr.fork is disabled

doc/gitlab.nvim.txt
Maybe this fixes #361? Not sure
=> change section name to match method being documented

config/emojis.json
Add the following emojis:
- :tada:
- :package:
- :rocket:
=> Chore: Add more emojis

.github/workflows/go.yaml, .github/workflows/lua.yaml, lua/gitlab/actions/discussions/tree.lua
Fixes bug where note creation would throw an error if the discussion tree was opened and then closed again. Fixes #437.
=> Fix Note Creation Bug

lua/gitlab/reviewer/init.lua
Fixes #453 by forcing linewise motion.
=> Fix: Force linewise motion in suggestion keybinding

lua/gitlab/job.lua
=> Fix: Prevent error after plenary job update

lua/gitlab/server.lua
Original here: https://github.com/harrisoncramer/gitlab.nvim/pull/436
=> fix: JSON on windows

lua/gitlab/health.lua
=> fix: do not show healthcheck alert for warnings

cmd/app/comment_helpers.go, lua/gitlab/actions/common.lua, lua/gitlab/actions/discussions/tree.lua, lua/gitlab/indicators/diagnostics.lua, lua/gitlab/reviewer/init.lua
=> Fix: Jumping to renamed files

lua/gitlab/actions/pipeline.lua
**Fixes:** 
1.  https://github.com/harrisoncramer/gitlab.nvim/issues/479
2. Fix and enahance pipeline retries. The new change will retry all pipelines for which a job will have failed . NOTE: unsure how the pipeline was being able to retrigger prior to this as the route defined in pipeline.go `/pipeline/trigger/` did not match the route called in pipeline.lua `/pipeline`. Had to change it to `/pipeline/trigger` to make it work 
**Test**
=> fix: linewise actions broken
