- lua/gitlab/comment.lua
- lua/gitlab/discussions.lua
- lua/gitlab/init.lua
- lua/gitlab/utils/init.lua
Moves all `require` calls to notify out of the scheduled calls and into the top of the module. This fixes a bug where the plugin would not load for a fresh environment without notify previously loaded.
> Fix Notify Requires

- lua/gitlab/discussions.lua
I found that if splitright was set to true the list of discussions would be populated in the right split and then the buffer would be taken over by the actual file. Leaving the left spilt blank. This just ensures that regardless of the users setting they open as expected.
> Ensure discussion splits open correctly

- README.md
- lua/gitlab/comment.lua
- lua/gitlab/discussions.lua
- lua/gitlab/init.lua
- lua/gitlab/job.lua
- lua/gitlab/utils/init.lua
Addresses some comments from Reddit who pointed out that you don't need to have notify as a dependency.
If folks want to use notify they can set the `vim.notify = require("notify")` in their own configuration.
> Feat: Remove Notify Dependency

- cmd/list_discussions.go
- lua/gitlab/discussions.lua
- lua/gitlab/utils/init.lua
This commit changes the filter on the API response so that we are only filtering out system level notes. This means we get notes that are not linked to specific locations in the code.
Subsequent work will have to separate these types of notes from the other code-linked notes and probably display them in some sort of separate tree.
> Feat: Pull down all non-code notes

- cmd/update.go
Was initializing a separate client (d'oh) should have just used the pre-initialized one with the base URL option set.
> Addresses issue with #20

- cmd/comment.go
- lua/gitlab/comment.lua
We weren't writing a 200 status code post-delete because Gitlab returns a 204 (empty but successful) by default. I updated this logic to change that and also to refresh the tree.
The collapsed state of the tree will be wiped out if you delete a bottom-level discussion but that's okay for now, not a high priority right now.
> Refresh Tree on Delete

- lua/gitlab/discussions.lua
- lua/gitlab/utils/init.lua
Three backticks will break the discussion tree, this MR specifically adds custom UUIDs to each text node to avoid this issue.
> Attach UUIDs to Discussion Text

- README.md
- cmd/main.go
- lua/gitlab/comment.lua
- lua/gitlab/discussions.lua
- lua/gitlab/init.lua
- lua/gitlab/keymaps.lua
- lua/gitlab/state.lua
- lua/gitlab/summary.lua
- lua/gitlab/utils/init.lua
Previously we were attempting to start up the Golang server whenever someone opened a feature branch. This was problematic because the plugin would try to look for an MR on feature branches where none existed yet.
This MR modifies the startup calls so that the server is only initialized after you run any of the commands provided by the plugin, as specified in the root module. This ensures that we'll only try to connect to Gitlab when the _user believes_ that an MR actually exists for the current feature branch.
> Bugfix: Don't Start Server Right Away

- cmd/approve.go
- cmd/comment.go
- cmd/main.go
- cmd/revisions.go
- cmd/revoke.go
- lua/gitlab/comment.lua
- lua/gitlab/init.lua
- lua/gitlab/state.lua
This MR refactors the comment creation endpoint to use the `go-gitlab` native approach to comment creation.
It does _not_ fix issues with creating comments on other lines like #25 points out. But hopefully it'll lay the groundwork for us fixing this in the future once we have a better way of detecting in the Lua code what values to send (primarily whether a line has been modified, added or deleted).
This will require more intelligent parsing of the GIT information of a given file when leaving the comment itself
> Cleanup of comment creation

- README.md
- cmd/job.go
- cmd/main.go
- lua/gitlab/actions/pipeline.lua
- lua/gitlab/state.lua
This MR lets you use `<leader>l` (the default keybinding) to trigger a "linewise" action when in the popup buffer. 
For the pipeline popup buffer, this grabs the logtrace (if it exists) for the current job and opens it in a new buffer.
> Feat: See Pipeline Job Logs

- README.md
- lua/gitlab/server.lua
- lua/gitlab/utils/init.lua
This MR adds support for Windows. The binary is installed as `bin.exe` and executed as per usual.
Since Windows does not have `make` natively I've also removed that as a dependency.
Addresses #34
> Feat: Windows Support

- README.md
- cmd/main.go
- lua/gitlab/server.lua
- lua/gitlab/state.lua
- lua/gitlab/utils/init.lua
Hi,
currently `gitlab.nvim` can be used only in one instance of neovim because there is only single port. Also when you open second neovim instance the server is not started silently (`http.Server` fails in go but the process still runs) but review is still opened and all API calls from second instance are sent to server which was started by first instance of neovim ( likely different gitlab project ).
I updated the start logic in lua and go in order to support random port which is chosen in go. This change is backward compatible so the `port` config option can still be used to specify port on which server should be started. Serve now have health check endpoint (`/ping`) and review is started only if this endpoint respond with HTTP status 200.
> Add option to choose random server port

- README.md
- after/syntax/gitlab.vim
- lua/gitlab/actions/discussions.lua
- lua/gitlab/colors.lua
- lua/gitlab/init.lua
- lua/gitlab/state.lua
- lua/gitlab/utils/init.lua
This adds syntax highlighting to the discussion tree. The syntax highlighting is configurable by providing any valid highlight group in the setup function. We can always expand this later to cover more things if we want to style more of the plugin.
> Feat: Add Color Configuration

- after/syntax/gitlab.vim
- lua/gitlab/utils/init.lua
1. Fixed regex for username. Now it supports`_-.` and Unicode symbols like German letters.
Here is example of usernames, which is valid, but didn't work before
```
@pötzsch 1 day ago 
@Aleksei.Sherchenkov 1 day ago 
@Aleksei-Sherchenkov 1 day ago 
@Aleksei_Sherchenkov-Second 1 day ago 
```
2. Fixed getting colors from HL groups. On my Mac in terminal, terminal using tmux and neovide it returned empty string. I took code from documentation of `vim.fn.hlID()`
> Fix highlight for usernames

- .github/workflows/go.yaml
- cmd/client.go
- cmd/git.go
- cmd/git_test.go
- cmd/main.go
- makefile
Some of my projects are in nested folders, e.g. https://custom-gitlab.com/folder-1/folder-2/project-name.git.
The regex used seems to only support one level of folder.
This pull request changes the golang server to support multiple nested folders.
I also added some unit tests to ensure the regex is working as expected.
Moreover, I added some CI to build and test the golang project.
> Feat: support nested folders in namespace

- README.md
- cmd/git.go
- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions.lua
- lua/gitlab/init.lua
- lua/gitlab/reviewer/diffview.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/state.lua
:wave: Hi,
this PR adds support for discussion sign and diagnostics. Diagnostics and signs are currently split on purpose ( even though the sign can be set also for diagnostic ) to have better control when multiline support will be added ( in this PR ). I will be testing this for few days to see if it works.
TODO:
* :heavy_check_mark: support multiline discussions for sign -> the idea is to have some main sign on line where the discussion is created and then other sign(s) ( maybe something like <--> but vertical ) if discussion is for multiple lines.
* :heavy_check_mark: support multiline discussions for diagnostics.
* currently the discussions are refreshed when file is switched / loaded in reviewer -> do we need periodic updates ? it would be maybe convenient :thinking: 
* …
> Discussion sign and diagnostics

- .github/workflows/tags.yaml
This MR adds the Github action that will automatically tag releases on every merge into main.
Since this is the start of our semantic versioning it is a #major bump to v1.
> Adds Tags Worfklow

- lua/gitlab/actions/pipeline.lua
- lua/gitlab/state.lua
This MR is a #patch fix that ensures you can provide a `.gitlab.nvim` file at the root of the git project and open up the reviewer at any level of the project.
> Fix: Allows you to open up gitlab.nvim even in nested directories

- .github/workflows/tags.yaml
This is another attempt to fix the tagging CI pipeline, to only check the latest commit (this one) for the tag, per this comment: https://github.com/anothrNick/github-tag-action/issues/292
> Fix: Change Branch History to Check "last" Only

- README.md
- lua/gitlab/actions/summary.lua
- lua/gitlab/state.lua
This commit makes it possible to show reviewers in the metadata panel of the Summary. It does not change the default configuration, though.
> Feat: Add reviewers to summary metadata

- README.md
While I was going through the README.md file I found a couple of typos that could be fixed easily.
> Docs: Fix typos in README.md

- cmd/server.go
Fixes an issue with the "shutdown" command. We need to check that the error returned is a non-shutdown error.
> Bugfix: Fixes Shutdown Error Handling

- lua/gitlab/actions/pipeline.lua
- lua/gitlab/utils/init.lua
Fixes pipeline output.
We had a naive solution that assumed names would not have whitespace characters, this fixes printing to pipeline buffer + getting local logs w/ whitespace
> Bugfix: Pipeline Job Names w/ Whitespace

- .github/workflows/tag-and-release.yaml
This will let us skip releases with the NONE keyword (no tags, no release) for small things like README tweaks or pipeline changes.
NONE
> Feat: Skip Tags + Releases

- README.md
- cmd/merge.go
- cmd/merge_test.go
- cmd/server.go
- cmd/test.go
- cmd/types.go
- lua/gitlab/actions/merge.lua
- lua/gitlab/actions/summary.lua
- lua/gitlab/init.lua
- lua/gitlab/reviewer/diffview.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/state.lua
- lua/gitlab/utils/init.lua
This adds the ability to merge an MR from within gitlab.nvim directly. If the reviewer is open, it'll be closed automatically. Users may configure whether they'd like to squash commits on the merge, as well as whether they'd like to delete the original source branch on a merge.
If squashing, users are prompted to provide an optional custom squash message for the squash commit.
> Feat: Adds Ability to Merge MR

- cmd/client.go
This missing service was causing errors (nil pointer exceptions) when attempting to retrigger a pipeline. This MR adds it back to the plugin.
> fix: Adds missing pipeline service

- lua/gitlab/actions/discussions/signs.lua
- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/reviewer/diffview.lua
- script.lua
This MR is an attempt to address some of the bugs/issues with discussion creation and note creation.
This is related to #128 which is occurring due to the Gitlab API's _extremely particular_ API surrounding line codes. This certainly doesn't fix all the issues but it solves a few different ones.
First, when you left a multiline ranged comment we were grabbing the CURRENT line rather than the top of your visual selection and using that as the start line, which caused issues. 
Another bug was related to leaving a comment on an unchanged line in the _new_ pane. This is solved now -- we look at the current line, and also at the linked line in the other reviewer pane. If the two are identical, then you are actually leaving a comment on an old diff, so we adjust the payload correctly.
> Fix: Discussion + Note Creation Bugs

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/reviewer/diffview.lua
- lua/gitlab/state.lua
After this MR, gitlab.nvim will attempt to use --imply-local parameter when opening diffview reviewer, based on a new configuration setting for gitlab.nvim, which is introduced as an "opt-in" option. Previous behavior is unchanged unless gitlab.nvim is configured by user to use the new feature.
The benefit of --imply-local is that diffview will treat the current HEAD that is being reviewed as a local file, allowing full use of diagnostics in the buffer, including LSP and linters.
In case the local working tree has changes compared to the state that is being reviewed, gitlab.nvim will not use the --imply-local parameter towards diffview, because that would could potentially show local file changes which are not part of the merge request under review. In this case a warning will be …
> Allow use of --imply_local when calling DiffviewOpen, allowing LSP use and linting in MR review

- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/reviewer/diffview.lua
This MR attaches to Diffview's hooks API to get the actual tabpage of a closed Diffview, so that we only register the `gitlab.nvim` reviewer as being closed when the tab numbers line up. Previously we were closing it whenever this event fired which didn't work because someone could have both Diffview and Gitlab open at the same time.
> Fix: De-Register Tabpage on Correct Close Event

- doc/gitlab.nvim.txt
- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/create_mr.lua
- lua/gitlab/actions/discussions/tree.lua
- lua/gitlab/actions/pipeline.lua
- lua/gitlab/actions/summary.lua
- lua/gitlab/utils/init.lua
This MR addressed the issue that empty lines in discussion tree nodes were removed in `glab.nvim` even if the comment was created correctly on Gitlab. However, if a comment with deleted empty lines was edited in `glab.nvim` and saved again, the change was made also on Gitlab.
Apart from the main issue, this MR also fixes some problems with new lines in the MR summary and when creating a new MR. There is still an open question whether to remove even the last trailing new line in these two cases. A trailing new line is removed from the code suggestion.
Finally, a recommended setting regarding the display of discussion trees is added to, and some typos are removed from the `REAMDE.md`.
Closes #170
> Fix: Keep empty lines in discussion tree

- lua/gitlab/actions/discussions/init.lua
This MR fixes an issue where someone could leave a note on an MR without opening the discussion tree first. We want to avoid throwing an error by attempting to update the discussion tree if it doesn't already exist.
> Fix: Allow Notes w/out Discussion Tree Open

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/actions/create_mr.lua
- lua/gitlab/state.lua
This mini PR makes it possible for users to configure the MR title input window.
It seems that "position" cannot be configured, but "size" is the most important anyway, to make writing long MR titles easier. Setting "border" is enabled just for UI consistency.
> Feat: Make MR title input window configurable

- lua/gitlab/actions/pipeline.lua
The pipeline popup can be shown on top of other popups, e.g., the summary or comment popups. When
the zindex of the pipeline popup is the same as that of the "lower" popup, its border is not
displayed correctly. This is fixed by increasing the zindex of the pipeline popup.
> Fix: Improve visibility of pipeline popup

- lua/gitlab/actions/comment.lua
- lua/gitlab/reviewer/diffview.lua
- lua/gitlab/utils/init.lua
This MR overhauls the logic that we previously had in place for determining payloads for creating comments.
Gitlab's API is notoriously awful when it comes to posting comments, because the actual content of the POST has to change depending on whether or not you are sending a comment on a modified line, an unchanged line, or a deleted line. 
This MR takes a very meticulous approach to determining what sort of change has occurred on the currently focused line. It does this by parsing the hunk headers and _actual content of the diff_ as well, to figure out whether the line has been added, changed, or untouched. It also takes advantage of Neovim's scroll lock functionality. If you are scrolling in the reviewer panel, the location of your cursor in the changed file and in the new file will be …
> Fix: Line Comment Refactor

- lua/gitlab/actions/discussions/annotations.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/state.lua
Resolves #185.
Also makes the Help keymap visible in the discussion tree's winbar.
> Fix toggle nodes not working properly after modifying notes

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/actions/discussions/annotations.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/emoji.lua
- lua/gitlab/state.lua
This PR tries to make toggling of the discussion tree a little more user friendly. It will:
- Enable toggling nodes from the note body
- Enable toggling resolved status from child nodes
- Add keymap for toggling tree type
Apart from that, it fixes a small bug which caused an error whenever the cursor moved to a `file_name` or `path` node in the "by_file_name" discussion tree.
> Feat: Improve discussion tree toggling

- lua/gitlab/actions/discussions/init.lua
When rapidly cycling through diffs we want to avoid running this function when the value is `nil`
> Add nil check

- lua/gitlab/hunks/init.lua
- lua/gitlab/indicators/signs.lua
We were not returning the aggregated line changes when a comment fell after all hunks in the new SHA
> fix: Calculate new line in ranged comment after all hunks correctly

- lua/gitlab/hunks/init.lua
- lua/gitlab/indicators/diagnostics.lua
Fixes an issue where diagnostics were not created properly when the diagnostic was on a deleted line
> fix: diagnostic creation for comments on deleted lines

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/state.lua
This MR deprecates the "backup" register which was a hot-fix used to deal with bugs upon comment and note creation
> fix: deprecate backup register

- cmd/git.go
- cmd/pipeline.go
- cmd/pipeline_test.go
- cmd/server.go
- cmd/test.go
- cmd/types.go
- lua/gitlab/actions/pipeline.lua
- lua/gitlab/actions/summary.lua
- lua/gitlab/async.lua
- lua/gitlab/init.lua
- lua/gitlab/state.lua
Addresses #218
This MR makes it possible to fetch the pipeline information on the main/master branch. It does so by removing the requirement that you open gitlab.nvim inside of a feature branch, and by making a call to [the latest pipeline for the current branch](https://docs.gitlab.com/ee/api/pipelines.html#get-the-latest-pipeline), rather than getting the pipeline ID from the "info" section of an MR.
> feat: enable pipeline command on main/master

- lua/gitlab/actions/discussions/init.lua
Trying to fix some problem in the review command of the plugin, as describe in [this github discussion](https://github.com/harrisoncramer/gitlab.nvim/discussions/221).
It concern mainly the following problems:
- ```terminal
Error executing lua: Vim:E5300: Expected a Number or a String
stack traceback:
[C]: in function 'bufnr'
...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:456: in function 'jump_to_file'
...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:832: in function <...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:830>
```
- ```
E5108: Error executing lua: ...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:467: Cursor position outside buffer
stack traceback:
[C]: in function 'nvim_win_set_cursor' …
```
> fix: correcting some problem with review mode

- lua/gitlab/actions/summary.lua
This fixes a bug introduced in the delete_branch/squash PR. Sorry for the trouble - I didn't test my PR properly and I got confused with what the new format of labels is.
> Fix: Treat INFO.labels as a table not as a string

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/merge.lua
- lua/gitlab/actions/miscellaneous.lua
- lua/gitlab/emoji.lua
- lua/gitlab/state.lua
This MR addresses #177. The user can now specify a list of registers in `settings.popup.temp_registers` to which the contents of editable popups will be saved when exiting the popup.
A couple of notes on things that might be done differently:
1. If no `temp_registers` are defined, nothing happens. Instead, when quitting a popup without a temp_register being set, the user could be notified about the possibility as mentioned in the original feature request #177.
2. The `temp_registers` are filled even when triggering `settings.popup.perform_action` because this also triggers the `exit` function with the callback `lua/gitlab/state.lua:259` that does the popup saving. If this behaviour is undesirable, the `popup_opts` could be extended to make it possible not to save upon `perform_action`. …
> Feat: Allow saving popup contents to temp_registers when quitting

- lua/gitlab/state.lua
The autocommand triggered on `BufWinLeave` still causes errors with unavailable buffers when pressing the `state.settings.popup.perform_linewise_action` keybinding in the Confirmation popup. This problem was there already with `BufUnload` because this keybinding is mapped to:
```lua
vim.keymap.set("n", M.settings.popup.perform_action, function()
local text = u.get_buffer_text(popup.bufnr)
if opts.action_before_close then
action(text, popup.bufnr)
exit(popup, opts)
else
exit(popup, opts)
action(text, popup.bufnr)
end
end, { buffer = popup.bufnr, desc = "Perform action" })
```
In this code block the `exit()` function is called (see bottom of message for full error traceback), which later calls `popup:unmount` and in turn `nvim_buf_delete` which triggers the `BufWinLeave` event, which causes …
> Fix: Autocommand causes errors on MR creation

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/state.lua
This PR adds a keybinding ("u" by default) to copy the URL of the current node in a discussion to system clipboard. This is useful if a user wants to share a link to a message outside of Neovim, e.g., in a messaging app.
Apart from this functionality, there is a fix (replace `require("gitlab").comment()` with `require("gitlab").create_comment()`) and some unification of style in the documentation.
> Feat: Add keymap to copy node URL to clipboard

- lua/gitlab/reviewer/init.lua
- lua/gitlab/utils/init.lua
Hi @harrisoncramer, here's a fix for a similar problem that you solved today -- this time at the end of a file that has fewer lines, so `jump_to_reviewer` tries to jump past the last line of a buffer. Now, the cursor moves to the last line and a warning is shown, instead of throwing an error.
> Fix: Cursor position beyond buffer end

- lua/gitlab/indicators/diagnostics.lua
Addresses #263. This is a simple fix, not sure whether the missing line number information for "file" comments should be handled in another place.
> Fix: File comments don't have line number information

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/state.lua
It is now possible to configure an authentication provider, that will be used to retreive the gitlab token via a lua function.
Fixes #269
> Add authentication provider setting

- lua/gitlab/actions/common.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/actions/draft_notes/init.lua
- lua/gitlab/indicators/common.lua
- lua/gitlab/utils/init.lua
Fixes a few different issues with empty states not refreshing properly and the winbar not refreshing properly when there is "no data" in a given discussion tree window pane.
> Fixes no draft notes, winbar issue

- lua/gitlab/indicators/diagnostics.lua
We need to check whether a diagnostic is in the old or new SHA, we can't just return the new line number.
> fix: Fixes line number for diagnostics in old sha

- cmd/draft_notes.go
- cmd/draft_notes_test.go
- lua/gitlab/actions/common.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/draft_notes/init.lua
- lua/gitlab/indicators/diagnostics.lua
Fixes issue with editing draft notes; jumping to correct position for draft notes; and replying (not supported) to draft notes.
> fix: draft note edits + reply keybinding

- lua/gitlab/actions/create_mr.lua
- lua/gitlab/actions/summary.lua
- lua/gitlab/git.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/utils/init.lua
This PR add the feature that the up-to-date status of the remote feature branch is checked before creating a MR and when starting a review or opening the summary.
When the remote/origin feature branch does not contain the local HEAD (checked with `git branch -r --contains <feature-branch>`), a message is shown:
1. For `gitlab.create_mr()` this is an error and the MR creation is aborted.
2. For `gitlab.review()` and `gitlab.summary()` this is just a warning.
> Feat: Check feature branch is up-to-date on remote

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/init.lua
It's cool that the draft mode can be toggled without restarting Neovim. This PR makes this functionality available for mapping outside of the discussion tree.
Also, this PR some `gitlab.toggle_resolved`, and `gitlab.reply` as global actions, since they require a `tree` as a parameter, and they do not work when run like `require("gitlab").reply()`.
> Feat: Make toggle_draft_mode available outside discussion tree

- cmd/draft_notes.go
- cmd/reply.go
- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/tree.lua
- lua/gitlab/actions/draft_notes/init.lua
This MR moves draft note _replies_ into the correct tree.
Previously, we did not distinguish between top-level draft notes and "draft replies" which are sent in response to an existing discussion. The Gitlab API requires you to specify the ID of the discussion you are replying to.
This MR updates the discussion tree and unlinked discussion tree to properly nest the draft replies under their respective discussions, and updates the draft notes modal to allow for posting live and draft replies.
> feat: support draft note replies

- lua/gitlab/hunks.lua
Addresses #247
The base_sha should be used for calculating the correct diff hunks because it is also used for the DiffviewOpen command.
The local base_branch could be out-of-sync with origin, so it is not reliable for diff hunk calculation.
> Fix: Use base_sha for calculating diff hunks

- lua/gitlab/actions/comment.lua
This PR fixes how backticks in code suggestions are identified:
1. The original iteration compared to the indeces, not to the values of the table of all lines.
2. The original regex didn't allow backtics with a filetype specification, e.g., "```bash".
> Fix: Use backticks in code suggestions

- lua/gitlab/actions/common.lua
This PR fixes a small mistake that caused the node url not to be copied.
> Fix: Copy node url to clipboard

- lua/gitlab/git.lua
This PR restores the `-r` flag for `git branch` that was removed by a recent refactor in order to list the `remote` branches for MR targets.
> Fix: List remote branches for merge targets

- lua/gitlab/git.lua
> fix(mr.create): consider remote branches

- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/miscellaneous.lua
- lua/gitlab/actions/summary.lua
This PR re-enables saving popup contents to temp_registers.
> Fix: Save popup contents to temp_registers

- README.md
- doc/gitlab.nvim.txt
- lua/gitlab/indicators/diagnostics.lua
- lua/gitlab/indicators/signs.lua
- lua/gitlab/state.lua
Addresses #302.
This PR also makes it possible to hide the diagnostic sign (e.g., `I` if the diagnostic level is "INFO") - this makes the diagnostic range icons better aligned. The default behaviour of the plugin does not change, i.e., the diagnostic signs are shown.
I've noticed one small bug that existed already with nvim 0.9, if some signs overlap, the `GitlabComment` icons are hidden by the `GitlabRange` icons the first time the signs are placed. This is because for some reason, this line in `lua/gitlab/indicators/signs.lua:33` does not return any already placed signs:
```lua
local existing_signs =
vim.fn.sign_getplaced(vim.api.nvim_get_current_buf(), { group = discussion_sign_name })[1].signs
```
On subsequent runs (e.g., when jumping to a diagnostic or when switching files in the …
> Fix: Ranged comment signs not showing

- doc/gitlab.nvim.txt
Hi Harry,
Thanks so much for writing this plugin. I've recently started a job at a company that uses Gitlab so I'm giving it a go. I noticed that the default value of `open_reviewer` when calling `choose_merge_request` was wrong in the docs, so here's a tiny PR to fix it.
Cheers!
> Fix docs: choose_merge_request's open_reviewer default value is true

- lua/gitlab/actions/summary.lua
- lua/gitlab/state.lua
This PR addresses #308.
The code for closing popups is quite complicated, so it would still benefit from a refactor. The `popup:unmount()` methods are called necessarily several times. This PR gets rid at least of some of these repeated calls and it also gets rid of the call to `vim.api.nvim_buf_delete()` in favour of the existing `exit(popup, opts)` function which has the advantage that the `nui` library makes sure there is something to be unmounted when `layout:unmount` or `popup:unmount` are called.
This PR also limits the `BufWinLeave` autocommands to just the buffers that actually need them.
> Fix: Failure when unloading buffer

- lua/gitlab/actions/merge_requests.lua
When choosing a merge request, I usually want to also see what branch is being merge into what target branch. This PR adds this information to the MR select menu.
> Feat: Add branch info to choose_merge_request menu

- config/emojis.json
Hi @harrisoncramer, I've noticed that simple `:hearts:` and `:heart:` emojis are missing in the list of supported emojis. I don't think you created the `config/emojis.json` by hand so maybe you don't expect the file to be modified manually. In any case, it would be nice to add these emojis.
The extra spaces in the `"moji"` fields are there on purpose, so that Neovim renders the symbols with adequate spacing.
> Chore: Add heart emoji

- README.md
- lua/gitlab/actions/common.lua
- lua/gitlab/actions/discussions/annotations.lua
- lua/gitlab/hunks.lua
- lua/gitlab/indicators/common.lua
- lua/gitlab/indicators/diagnostics.lua
- lua/gitlab/utils/init.lua
This PR is an attempt to improve diagnostic placement and `jump_to_reviewer` behaviour reported in #158.
It introduces the following changes:
1. The position of a diagnostic and for `jump_to_reviewer` is calculated with a common function, reducing the potential for incorrect jumps
2. The position for ranged diagnostics is based on the `first_note.position.new_line` or `first_note.position.old_line`, rather than the `line_code` - in my experience, this tends to be the most accurate source of information about where to place diagnostics, see example below. The information in the `line_code`s is used to calculate the length of the diagnostic range, though.
3. Old SHA detection is improved. Relying on the `old_line` only is not always reliable, I've come across notes that had a non-nil …
> Fix diagnostic position when sha changes

- after/syntax/gitlab.vim
#339 introduced some regressions in discussion tree highlighting. This PR fixes:
1. expander highlighting in sub-nodes
2. highlighting of usernames with dots (e.g., `@name.surname`)
3. separate highlighting for mentions (different from `GitlabUsername`)
> Fix: Discussion tree highlighting

- README.md
- cmd/merge_requests.go
- cmd/merge_requests_test.go
- doc/gitlab.nvim.txt
- lua/gitlab/actions/merge_requests.lua
- lua/gitlab/async.lua
- lua/gitlab/state.lua
Solves #338 
Let me know if this change works:
1. Changed `/merge_request` from GET to POST
2. choose_merge request in `state.lua` now accepts a Lua table acting as gitlab params. Also changed refresh to true
> Add filtering when choosing merge requests

- lua/gitlab/health.lua
Hi @harrisoncramer, I didn't have the time to react to your [comment](https://github.com/harrisoncramer/gitlab.nvim/pull/345#issuecomment-2291539147) on your initial MR for the health check. Now that I've given it a try, I've found a bug in the check for removed config fields, so here's a fix.
> Fix: Error with removed config fields

- doc/gitlab.nvim.txt
- lua/gitlab/reviewer/init.lua
The keybindings `s` and `c` in the Reviewer windows now accept a count. It works like this:
- `3sj` is identical to `s3j` - create a suggestion for the current and three more lines
- `3ss` or `s3s` - create a suggestion for three lines (including the current one)
- the same principal applies to `c` mappings
This is equivalent to how built-in keybindings like `3dj`, `d3j`, `3dd`, and `d3d` work.
Unlike with builtin operators `d`, `c`, etc. the operator count and motion count are NOT multiplied, so that the following key presses `3s2s` are not equivalent to `6ss` but result in `s32s`.
> Feat: Accept count with commenting keybindings

- doc/gitlab.nvim.txt
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/state.lua
This PR makes it possible to customize the behavior when pressing the `move_to_discussion_tree` keybinding in the reviewer and there is no diagnostic under the cursor. Users can now set up any combination of:
- show warning
- jump to last position in discussion tree
Closes #309.
> Feat: Enable always jumping to discussion tree

- lua/gitlab/actions/help.lua
Hello,
This PR make the help popup not editable by calling switch_can_edit_buf with false.
It also add a popup listener to automatically close the help popup when the buffer is leaved.
> Make help popup not editable and close it on BufLeave

- cmd/app/config.go
- cmd/app/server.go
- lua/gitlab/actions/merge_requests.lua
- lua/gitlab/server.lua
- lua/gitlab/state.lua
> fix: Fixes MR selection if there are multiple targets

- cmd/app/label.go
- cmd/app/merge_requests.go
- cmd/app/merge_requests_test.go
- cmd/app/server.go
- doc/gitlab.nvim.txt
- lua/gitlab/reviewer/init.lua
- lua/gitlab/state.lua
This MR makes it possible to query for MRs that have already been merged or closed, among a variety of other query parameters.
The full list of query options can be found here: https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests
Unfortunately Gitlab's API does not support the use of OR operators, which means that it's not possible to perform queries such as "Give me all MRs that have me as an assignee OR a reviewer OR an author" which would be useful. I'm considering adding this into the plugin, and aggregating the results from these API calls running in parallel, but may do that as a separate MR.
Addresses #321
> feat: Improve MR selection

- lua/gitlab/actions/comment.lua
- lua/gitlab/reviewer/init.lua
Stricter checks for when someone attempts to leave a comment in the wrong place. We are now checking for attempted comments in the file tree (wrong) and the discussion tree (also wrong). We are now not opening the layout entirely, instead of erroring on the actual attempt to create a comment.
You can replicate this error if you call `require("gitlab").create_comment()` while hovering over either of those locations.
> fix: Add better checks for leaving comments

- lua/gitlab/reviewer/init.lua
This PR fixes a bug I introduced in the default keybindings for commenting (with or without a suggestion) on a single line.
Fixes #370.
> Fix: Comment on single line selects two lines

- cmd/app/assignee_test.go
- cmd/app/attachment_test.go
- cmd/app/comment_test.go
- cmd/app/create_mr_test.go
- cmd/app/draft_note_publisher_test.go
- cmd/app/draft_notes_test.go
- cmd/app/job_test.go
- cmd/app/list_discussions_test.go
- cmd/app/merge_mr_test.go
- cmd/app/merge_requests_by_username_test.go
- cmd/app/merge_requests_test.go
- cmd/app/middleware.go
- cmd/app/middleware_test.go
- cmd/app/reply_test.go
- cmd/app/resolve_discussion_test.go
- cmd/app/server.go
- lua/gitlab/actions/comment.lua
I'd introduced a middleware pattern that was validating structs. The middleware was set up in the server with pointers to structs, like this:
```go
m.HandleFunc("/mr/merge", middleware(
mergeRequestAccepterService{d, gitlabClient},
withMr(d, gitlabClient),
withPayloadValidation(methodToPayload{http.MethodPost: &AcceptMergeRequestRequest{}}), // Here...
withMethodCheck(http.MethodPost),
))
```
This caused the struct data to be shared across requests! This was causing issues where payload fields were being shared between API calls. We want new payloads for every API call. 
This MR adjusts the code to add a new factory function on the `methodToPayload` map that creates a new payload per request so that data is not shared across them.
The new pattern is like this:
```go …
```
> fix: Fixes issues w/ shared pointers to structs

- lua/gitlab/reviewer/init.lua
- lua/gitlab/utils/init.lua
When jumping to the reviewer for a comment on an unchanged line, that line may be in a fold which DiffView closes every time. After jumping to that note a couple of times, this is a little annoying, so in this MR, I have the fold opened automatically.
> Feat: Automatically open fold under cursor

- cmd/app/draft_notes.go
Discussion ID is not required when leaving a new draft note comment.
> fix: discussion ID is not required

- lua/gitlab/actions/draft_notes/init.lua
- lua/gitlab/server.lua
This fixes an issue where running `require("gitlab").publish_all_drafts()` would result in the error `gitlab.nvim: Could not parse JSON request body: json: cannot unmarshal array into Go value of type app.DraftNotePublishRequest` because of empty `body` in `lua/gitlab/actions/draft_notes/init.lua` line 87.
```lua
M.confirm_publish_all_drafts = function()
local body = {}
```
Besides, this adds a notification to the user when the server is successfully built.
> Fix: Publish all drafts

- lua/gitlab/actions/common.lua
Refreshing the discussion tree made it modifiable because of a missing call of `gitlab.actions.common.switch_can_edit_bufs(false, v.bufnr)`.
> fix: make discussion tree buffers nomodifiable

- lua/gitlab/actions/create_mr.lua
- lua/gitlab/actions/summary.lua
- lua/gitlab/git.lua
- lua/gitlab/reviewer/init.lua
This MR updates the function that checks the stability of the branch and MR.
There is now one function responsible for checking whether the current branch is ahead/behind it's tracking branch. That function will warn the user if that's the case for all three possibilites (ahead, behind, or ahead and behind).
The second function is responsible for alerting the user if the status of the current MR is bad: merged, closed, or with conflicts.
These should address the points outlined in the issue outlined by Jakub. For instance, in the complex case where the user is setup to track a remote and they are behind the remote, and the MR associated with that remote has already been closed, they will get both warnings, which is accurate.
Plesae @jakubbortlik give this a look when you have time. …
> fix: Incorrect warning about commits

- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/utils/list.lua
> Fix: Show draft replies in the correct tree

- cmd/app/config.go
- cmd/app/middleware.go
- lua/gitlab/actions/merge_requests.lua
- lua/gitlab/server.lua
- lua/gitlab/state.lua
We'll use the internal ID of the Merge Request rather than the source/target branch when a specific MR is chosen, which is guaranteed to be unique and will avoid situations where we pass along a source/target relationship that is not unique. This is unusual but technically still possible if someone is repeatedly opening MRs against a branch (say main) from another branch, merging them and deleting the source branch, then re-creating a new MR with the same branch.
> 388 cannot choose merge requests

- config/emojis.json
When updating the `emojis.json` I made a mistake for the :tada: emoji. The emoji could be selected and awarded, but it was not shown in the `gitlab.nvim` UI.
This PR fixes it.
> Fix: Use correct name for emoji

- lua/gitlab/actions/comment.lua
This PR fixes the following issue.
The discussion tree can be opened in a tab different than the `Diffview` reviewer tab. This is quite practical if you want to see comments/suggestions next to an *editable* version of the reviewed files. However, replying to comments in such a "detached" discussion tree fails because the `gitlab.actions.comment.create_comment_layout` function verifies that we are in the reviewer tab, and it is also called for `gitlab.actions.discussions.init.reply`, even if the checks are not necessary for a reply.
> Fix: Enable replying if discussion tree is in a different tab

- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/tree.lua
This PR improves the user experience in the discussion tree by restoring cursor position after rebuilding the tree. This makes navigation in the discussion tree more fluent without the cursor jumping to the first line of the tree after actions like resolving discussions, adding new comments, publishing drafts etc.
> Fix: Restore cursor when updating from outside of tree

- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/annotations.lua
- lua/gitlab/utils/init.lua
This PR closes #411 by implementing the following:
- non-resolvable notes are added to the winbar as `comments` (this is done for inline comments too, even though I don't think there can be any non-resolvable inline comments, however, it makes the code a little cleaner (no need for checking some `nil` values) and it makes it safer in the strange case that there actually would be a non-resolvable inline discussion).
- `resolved` is changed to `threads`
- the order in showing threads is changed from `total/resolved` to `resolved/total`
- the words, `comments, threads, drafts` are used in the correct number if there's just 1 of them
> Fix: Show non-resolvable notes in winbar

- cmd/app/comment_helpers.go
- lua/gitlab/actions/comment.lua
- lua/gitlab/annotations.lua
- lua/gitlab/hunks.lua
- lua/gitlab/indicators/common.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/reviewer/location.lua
Makes it not possible to leave comments on renamed files
> fix: comment creation should not be possible for renamed and moved files

- lua/gitlab/colors.lua
- lua/gitlab/utils/init.lua
Delay the function call that sets color highlights until Neovim is fully set up and loaded
> fix: color highlight groups are invalid

- lua/gitlab/actions/approvals.lua
- lua/gitlab/actions/assignees_and_reviewers.lua
- lua/gitlab/actions/labels.lua
- lua/gitlab/actions/summary.lua
Hi @harrisoncramer, this is an implementation of #401. I've marked it as a draft because it will need some reworking if #426 is merged in. I'd be grateful if you could review it and consider including it in the plugin.
With this PR, when the Summary popup is open the following items in the Details are updated automatically when the user runs a command that changes the MR state:
- Updated
- Status
- Assignees
- Reviewers
- Labels
> Feat: Automatically update MR summary details

- doc/gitlab.nvim.txt
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/winbar.lua
- lua/gitlab/actions/draft_notes/init.lua
- lua/gitlab/annotations.lua
- lua/gitlab/init.lua
- lua/gitlab/state.lua
- lua/gitlab/utils/init.lua
Hi @harrisoncramer, this is an attempt to implement #409.
With this PR, the winbar shows the time since the last update of the discussion data and it shows a simple animation when the data is being reloaded.
There are some shortcomings that would require some more work to solve:
1. The winbar has become quite crammed when using position `left` or `right` for the discussion tree, so that the "Inline Comments" section can easily move outside of the window. To fix this, we'd have to add some more elaborate winbar string calculation that would take the window width and the components into account. This can be done in a separate follow-up PR, I believe
2. The drafts data are loaded significantly faster* than regular discussion data, this results in a short inconsistency in the winbar when …
> Feat: Show update progress in winbar

- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/merge_requests.lua
- lua/gitlab/git.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/utils/init.lua
Hi @harrisoncramer, in this PR I address #424, by making the following changes:
1. All checks whether a comment can be created are now made for all three functions: `create_comment`, `create_comment_suggestion` and `create_multiline_comment` in a dedicated function `gitlab.actions.comment.can_make_comment()`.
2. The checks are made in a more meaningful order (e.g., checking that cursor is in the reviewer is made before the check that current mode is visual mode for multiline comments).
3. The check for clean working tree before making comments is now correct and it's made on a per-file basis, i.e., unsaved/uncommitted changes in a different file do not block a comment in a good file.
4. Similarly, with a dirty working tree, choosing a MR is not blocked if that would not lead to switching …
> Fix: Checking whether comment can be created

- lua/gitlab/actions/discussions/winbar.lua
This is a cosmetic change to the winbar.
The "resolved" checkmark is now directly after the number of resolved threads, e.g., "1✓/5". I find this more readily comprehensible than "1/5✓".
The drafts are now shown *after* the unlinked comments - this makes the winbar text more stable when adding / removing drafts, as the number of threads is always placed next to unlinked comments.
> fix: improve indication of resolved threads and drafts

- .github/CONTRIBUTING.md
- README.md
- doc/gitlab.nvim.txt
Hi @harrisoncramer, I've updated various parts of the documentation a little.
This also covers the changed in the closed PR #430.
> Docs: Various minor improvements

- cmd/app/client.go
This MR changes the configuration to the HTTP client so that it doesn't retry failed attempts. This behavior was causing problems when Gitlab fails with a 500 status code, but actually publishes something.
> Fix: Remove Retry Logic

- lua/gitlab/actions/common.lua
- lua/gitlab/reviewer/init.lua
> Fix: Don't jump to file if it doesn't exist

- doc/gitlab.nvim.txt
- lua/gitlab/actions/summary.lua
- lua/gitlab/state.lua
This is a small PR that adds the MR's Web URL to the Details of the summary popup. I sometimes find it useful to be able to *see* the URL. A workaround is to use `glu` to copy the url to clipboard and then it is shown in a message, but sometimes I just don't want to pollute the clipboard just to see a piece of information.
> Feat: Add MR URL to the summary details

- doc/gitlab.nvim.txt
- lua/gitlab/actions/common.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/annotations.lua
- lua/gitlab/indicators/common.lua
- lua/gitlab/indicators/diagnostics.lua
Addresses the issue described in [this comment](https://github.com/harrisoncramer/gitlab.nvim/pull/470#issuecomment-2632298958).
This fixes the diagnostics placement while also making cycling Diffview files faster by pre-computing diagnostics and removing unnecessary list filtering.
> fix: make cycling reviewed files faster

- .github/CONTRIBUTING.md
- cmd/app/pipeline.go
- cmd/app/pipeline_test.go
- lua/gitlab/actions/pipeline.lua
Solves https://github.com/harrisoncramer/gitlab.nvim/issues/464
Uses the [List pipeline trigger jobs](https://docs.gitlab.com/ee/api/jobs.html) api end point to retrieve the jobs triggered by the root pipeline. The jobs in these pipelines are then retrieved by [List pipeline jobs](https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs) api and populated in neovim front end as shown in the screenshot below
---
Pipeline popup window when pipeline has trigger jobs
> feat(pipeline): display trigger jobs for a pipeline in the pipelines popup 

- lua/gitlab/actions/create_mr.lua
- lua/gitlab/popup.lua
When I'm creating a MR, I typically want to see the source branch because it usually contains some useful info like an issue code. If you @harrisoncramer think that some users might want to hide this information from the Create MR popup, I can make it configurable.
> Feat: Add source branch to create mr popup

- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/actions/discussions/winbar.lua
Fixes #480.
- Fixes jumping to discussion tree if `Notes` are focused instead.
- Also fixes jumping to the discussion tree when it's closed.
- Improves some docstrings and type annotations.
> Fix: Jumping to discussion tree

- lua/gitlab/actions/comment.lua
- lua/gitlab/actions/discussions/init.lua
- lua/gitlab/annotations.lua
- lua/gitlab/hunks.lua
- lua/gitlab/indicators/common.lua
- lua/gitlab/popup.lua
- lua/gitlab/reviewer/init.lua
- lua/gitlab/reviewer/location.lua
- lua/gitlab/utils/init.lua
Resolves #475.
Hi @harrisoncramer, I'd be grateful if you could review this PR. It resolves #475 by doing the following:
1. Reviewer data are collected *before creating* the comment popup, not just *before confirming* the comment.
2. The reviewer data are now managed *inside* of the `Location` class.
I'll add some more comments to the changed code itself.
> Fix: Store reviewer data before creating comment popup

- cmd/app/client.go
- lua/gitlab/actions/draft_notes/init.lua
- lua/gitlab/git.lua
- lua/gitlab/job.lua
This PR attempts to fix #425.
By default the gitlab client attempts [5 retries](https://gitlab.com/gitlab-org/api/client-go/-/blob/89e6601b09ec7702973fda7d24358e7bc59e197c/gitlab.go#L326) which corresponds to the fact that it bulk publishing drafts "fails" with a server error, it still creates 1+5 copies of the comments.
Apart from finally removing the retry functionality, this MR also introduces the following improves:
- Check that the local repository is up-to-date with remote before publishing drafts (bulk or single), as I've found that draft publishing can fail when commits have been added to the MR between creating drafts in `gitlab.nvim` and publishing them (probably just when there is a comment on some code that has changed).
- Show explanation what to do when publishing drafts …
> Fix: Make publishing drafts more robust

- cmd/app/comment_helpers.go
- lua/gitlab/actions/comment.lua
- lua/gitlab/reviewer/init.lua
This PR fixes #486 by restoring how old paths for (potentially) renamed files are handled. This requires rebuilding the Go server.
This PR fixes also the correct OLD/NEW file name assignment in the reviewer data and also the way how the file name for the comment popup title is created based on the reviewer data.
> Fix: Swap file_name and old_file_name in reviewer data

- cmd/app/client.go
- cmd/app/config.go
- doc/gitlab.nvim.txt
- lua/gitlab/state.lua
> Proxy Support
